name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build rundeck
      run: cd rundeck && docker build . --file Dockerfile --tag ttl.sh/rundeck-4.12:1d --push
    - name: Build rundeck node
      run: cd node-demo && docker build . --file Dockerfile --tag ttl.sh/rundeck-node:1d --push
    - name: Build rundeck client
      run: cd client && docker build . --file Dockerfile --tag ttl.sh/rundeck-client:1d --push
    - name: Build pdm ci
      run: docker build . --file pdm-ci.Dockerfile --tag ttl.sh/pdm-ci-python310-slim:1d --push
    - name: Build python 3.10 slim ci
      run: docker build . --file python.Dockerfile --tag ttl.sh/python310-slim:1d --push
    
        


